---
#
# First thing: update APT cache, upgrade packages and install utilities, prep the system for
# installing any other package (such as the firewall).
#

- name: Configure core repositories
  template: src=etc_apt_sources.list.j2 dest=/etc/apt/sources.list

- name: Update APT cache
  apt: update_cache=yes cache_valid_time=3600

- name: Install latest updates
  apt: upgrade=safe

- name: Install essential utilities
  apt: pkg={{ item }} state=installed
  with_items:
    - byobu
    - fish
    - htop
    - iftop
    - iotop
    - mosh
    - multitail
    - python-software-properties
    - update-manager-core

#
# Firewall: let's lock down the system as soon as possible.
#

- name: Install ufw
  apt: pkg=ufw state=present

- name: Enable logging
  ufw: logging=on

- name: Allow SSH port from certain network blocks
  ufw: rule=allow port=ssh proto=tcp src={{ item }}
  with_items: ssh_allowed_networks

- name: Enable ufw
  ufw: policy=deny state=enabled

#
# Configure the deployment user before disabling root access through SSH.
#

- name: Create deploy group
  group: name=deploy state=present

- name: Create deploy user
  user: name=deploy comment="Ansible Deploy User" group=deploy groups=sudo password="{{ deploy_password }}" shell=/usr/bin/fish

- name: Authorize ssh key for deploy user
  authorized_key: user=deploy key="{{ deploy_authorized_key }}" state=present

#
# Tighten up SSH
#

- name: Disable SSH login for root user
  lineinfile: dest=/etc/ssh/sshd_config regexp=^PermitRootLogin line="PermitRootLogin no" state=present
  notify: reload ssh

- name: Disable password-based authentication for SSH
  lineinfile: dest=/etc/ssh/sshd_config regexp=^PasswordAuthentication line="PasswordAuthentication no" state=present
  notify: reload ssh

#
# Further tighten up SSH by installing fail2ban.
#

- name: Install fail2ban
  apt: pkg=fail2ban state=installed

- name: Ensure fail2ban is started
  service: name=fail2ban state=started

#
# Enable automatic updates.
#

- name: Install unattended-upgrades
  apt: pkg={{ item }} state=present
  with_items:
    - unattended-upgrades
    - update-notifier-common

- name: Configure unattended-upgrades
  copy: src=etc_apt_apt.conf.d_20auto-upgrades dest=/etc/apt/apt.conf.d/20auto-upgrades

- name: Configure unattended-upgrades sources
  template: src=etc_apt_apt.conf.d_50unattended-upgrades.j2 dest=/etc/apt/apt.conf.d/50unattended-upgrades

